# Generated by Django 4.1 on 2022-08-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_feature_details_feature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
